#!/bin/bash

IFS=';' read -ra RES <<< "$BLOCK_INSTANCE"
TOP=$(ps -eo "${RES[1]}",args --sort=-"${RES[1]}" --no-headers | head -n 1)

# Split into a space deliminated array
# 0: CPU usage
# 1: Process name
#>2: Process arguments
IFS=' ' read -ra TOP <<< "$TOP"

# Split the process name to get the process name, not the path
IFS='/' read -ra PROC <<< "${TOP[1]}"

# Concat the args into one var
for ((i=2;i<"${#TOP[@]}";i++)); do
	ARGS+="${TOP[i]} "
done

if [[ "${RES[0]}" = "name" ]]; then
	echo "${PROC[-1]}"
	echo "${PROC[-1]}"
elif [[ "${RES[0]}" = "perc" ]]; then
	echo "${TOP[0]}%"
	echo "${TOP[0]}%"
fi

